// Mate-in-1 puzzles for beginners

export const puzzles = [
  {
    id: 1,
    title: '퀸으로 체크메이트!',
    description: '퀸을 움직여서 킹을 잡아봐! 👑',
    fen: '6k1/5ppp/8/8/8/8/5PPP/4Q1K1 w - - 0 1',
    solution: { from: 'e1', to: 'e8' },
    hint: '퀸을 맨 위로 올려봐!',
  },
  {
    id: 2,
    title: '룩으로 체크메이트!',
    description: '룩을 움직여서 체크메이트를 만들어봐! 🏰',
    fen: '6k1/5ppp/8/8/8/8/R4PPP/6K1 w - - 0 1',
    solution: { from: 'a2', to: 'a8' },
    hint: '룩을 맨 위로 올려봐!',
  },
  {
    id: 3,
    title: '비숍의 대각선 공격!',
    description: '비숍으로 체크메이트를 만들어봐! ⛪',
    fen: 'r1bk3r/pppp1Bpp/2n2q2/4p3/2B1P3/8/PPPP1PPP/RN1QK1NR w KQ - 0 1',
    solution: { from: 'c4', to: 'f7' },
    hint: '비숍을 대각선으로 옮겨봐! f7을 노려봐!',
  },
  {
    id: 4,
    title: '퀸의 강력한 한 수!',
    description: '퀸 하나로 게임을 끝내봐! 💪',
    fen: 'rnb1kbnr/pppp1ppp/8/4p3/6Pq/5P2/PPPPP2P/RNBQKBNR b KQkq - 0 1',
    solution: { from: 'h4', to: 'e1' },
    hint: '퀸을 킹 쪽으로 보내봐!',
    playerColor: 'b',
  },
  {
    id: 5,
    title: '나이트의 특별한 점프!',
    description: '나이트로 체크메이트를 만들어봐! 🐴',
    fen: '5rk1/5ppp/8/8/8/4N3/5PPP/6K1 w - - 0 1',
    solution: { from: 'e3', to: 'f5' },
    hint: '나이트를 ㄱ자로 점프시켜봐! 어디로 가면 킹이 도망 못 갈까?',
  },
  {
    id: 6,
    title: '백 투 더 랭크!',
    description: '룩으로 마지막 줄 체크메이트! 🎯',
    fen: '3r2k1/5ppp/8/8/8/8/5PPP/R5K1 w - - 0 1',
    solution: { from: 'a1', to: 'a8' },
    hint: '마지막 줄로 룩을 보내봐!',
  },
  {
    id: 7,
    title: '퀸 + 킹 협동!',
    description: '퀸으로 체크메이트를 완성해봐! 🤝',
    fen: '7k/5Q2/5K2/8/8/8/8/8 w - - 0 1',
    solution: { from: 'f7', to: 'g7' },
    hint: '퀸을 킹 가까이로!',
  },
  {
    id: 8,
    title: '두 개의 룩!',
    description: '룩 두 개로 체크메이트! 🏰🏰',
    fen: '7k/R7/8/8/8/8/8/R5K1 w - - 0 1',
    solution: { from: 'a1', to: 'a8' },
    hint: '다른 룩을 마지막 줄로!',
  },
  {
    id: 9,
    title: '폰이 영웅이 되는 순간!',
    description: '폰을 프로모션시켜서 체크메이트! 🦸',
    fen: '5k2/4P1K1/8/8/8/8/8/8 w - - 0 1',
    solution: { from: 'e7', to: 'e8' },
    hint: '폰이 퀸이 되면 체크메이트야!',
  },
  {
    id: 10,
    title: '퀸의 마지막 일격!',
    description: '퀸으로 화려하게 체크메이트! ✨',
    fen: 'r1b1kb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 0 1',
    solution: { from: 'h5', to: 'f7' },
    hint: 'f7은 약한 칸이야! 퀸으로 공격해봐!',
  },
];
