// Baduk puzzle data for beginners
// B=1 (BLACK), W=2 (WHITE)
const B = 1, W = 2;

export const puzzles = [
  // Capture puzzles: "이 돌을 잡아봐!"
  {
    id: 1,
    type: 'capture',
    title: '이 돌을 잡아봐! (1)',
    emoji: '🎯',
    hint: '⚪백돌의 활로가 1개 남았어요! 막아봐요!',
    boardSize: 9,
    board: [
      {r:4,c:4,color:W},
      {r:3,c:4,color:B}, {r:5,c:4,color:B}, {r:4,c:3,color:B},
    ],
    correct: [{r:4,c:5}],
  },
  {
    id: 2,
    type: 'capture',
    title: '이 돌을 잡아봐! (2)',
    emoji: '🎯',
    hint: '⚪백돌 2개가 연결돼 있어요. 활로를 찾아봐요!',
    boardSize: 9,
    board: [
      {r:4,c:4,color:W}, {r:4,c:5,color:W},
      {r:3,c:4,color:B}, {r:3,c:5,color:B},
      {r:5,c:4,color:B}, {r:5,c:5,color:B},
      {r:4,c:3,color:B},
    ],
    correct: [{r:4,c:6}],
  },
  {
    id: 3,
    type: 'capture',
    title: '이 돌을 잡아봐! (3)',
    emoji: '🎯',
    hint: '구석에 있는 ⚪백돌! 활로가 적어요!',
    boardSize: 9,
    board: [
      {r:0,c:0,color:W},
      {r:0,c:1,color:B},
    ],
    correct: [{r:1,c:0}],
  },
  {
    id: 4,
    type: 'capture',
    title: '큰 그룹을 잡아봐!',
    emoji: '💥',
    hint: '⚪백돌 3개의 마지막 활로를 찾아봐요!',
    boardSize: 9,
    board: [
      {r:3,c:3,color:W}, {r:3,c:4,color:W}, {r:3,c:5,color:W},
      {r:2,c:3,color:B}, {r:2,c:4,color:B}, {r:2,c:5,color:B},
      {r:4,c:3,color:B}, {r:4,c:4,color:B}, {r:4,c:5,color:B},
      {r:3,c:2,color:B},
    ],
    correct: [{r:3,c:6}],
  },
  // Escape puzzles: "도망쳐!"
  {
    id: 5,
    type: 'escape',
    title: '도망쳐! (1)',
    emoji: '🏃',
    hint: '⚫흑돌의 활로가 1개! 아래쪽으로 도망가요!',
    boardSize: 9,
    board: [
      {r:3,c:3,color:B},
      {r:2,c:3,color:W}, {r:3,c:2,color:W}, {r:3,c:4,color:W},
    ],
    correct: [{r:4,c:3}],
  },
  {
    id: 6,
    type: 'escape',
    title: '도망쳐! (2)',
    emoji: '🏃',
    hint: '⚫흑돌 2개를 살려야 해요!',
    boardSize: 9,
    board: [
      {r:4,c:4,color:B}, {r:4,c:5,color:B},
      {r:3,c:4,color:W}, {r:3,c:5,color:W},
      {r:5,c:4,color:W}, {r:5,c:5,color:W},
      {r:4,c:3,color:W},
    ],
    correct: [{r:4,c:6}],
  },
  {
    id: 7,
    type: 'escape',
    title: '구석에서 도망쳐!',
    emoji: '🏃',
    hint: '구석은 활로가 적어요! 어디로 도망갈까요?',
    boardSize: 9,
    board: [
      {r:0,c:0,color:B},
      {r:0,c:1,color:W},
    ],
    correct: [{r:1,c:0}],
  },
  // Territory puzzles: "집을 만들어봐!"
  {
    id: 8,
    type: 'territory',
    title: '집을 만들어봐! (1)',
    emoji: '🏠',
    hint: '빈 곳을 둘러싸서 집을 완성해요!',
    boardSize: 9,
    board: [
      {r:0,c:0,color:B},{r:0,c:1,color:B},{r:0,c:2,color:B},
      {r:1,c:0,color:B},
      {r:2,c:0,color:B},{r:2,c:1,color:B},
    ],
    correct: [{r:1,c:2}],
  },
  {
    id: 9,
    type: 'territory',
    title: '집을 만들어봐! (2)',
    emoji: '🏠',
    hint: '변에서 집을 만들어봐요!',
    boardSize: 9,
    board: [
      {r:0,c:3,color:B},{r:0,c:4,color:B},{r:0,c:5,color:B},{r:0,c:6,color:B},
      {r:1,c:3,color:B},{r:1,c:6,color:B},
      {r:2,c:3,color:B},{r:2,c:4,color:B},{r:2,c:6,color:B},
    ],
    correct: [{r:2,c:5}],
  },
  {
    id: 10,
    type: 'territory',
    title: '큰 집을 완성해!',
    emoji: '🏰',
    hint: '한 곳만 막으면 큰 집이 완성돼요!',
    boardSize: 9,
    board: [
      {r:6,c:0,color:B},{r:6,c:1,color:B},{r:6,c:2,color:B},{r:6,c:3,color:B},
      {r:7,c:3,color:B},
      {r:8,c:3,color:B},
    ],
    correct: [{r:8,c:4}],
  },

  // ===== 2수 퍼즐 (⭐⭐) =====
  // 축머리(ladder): 상대 돌을 쫓아가며 잡기
  {
    id: 11,
    type: 'ladder',
    title: '축머리! 쫓아가자 (1)',
    emoji: '🏃',
    hint: '⚪백돌을 계속 쫓아가요! 활로를 줄여봐!',
    boardSize: 9,
    multiMove: true,
    board: [
      {r:3,c:3,color:W},
      {r:2,c:3,color:B},{r:3,c:2,color:B},
      {r:4,c:4,color:B},
    ],
    // 흑이 (3,4)에 두면 → 백 활로 1개 → 백이 (2,4)로 도망 → 흑 (2,5)로 잡기
    correct: [{r:3,c:4}],
    opponentMove: {r:2,c:4,color:W},
    secondCorrect: [{r:2,c:5}],
  },
  {
    id: 12,
    type: 'ladder',
    title: '축머리! 쫓아가자 (2)',
    emoji: '🏃',
    hint: '도망가는 ⚪백돌을 막아요!',
    boardSize: 9,
    multiMove: true,
    board: [
      {r:4,c:4,color:W},
      {r:3,c:4,color:B},{r:4,c:3,color:B},
      {r:5,c:5,color:B},
    ],
    correct: [{r:4,c:5}],
    opponentMove: {r:3,c:5,color:W},
    secondCorrect: [{r:3,c:6}],
  },
  {
    id: 13,
    type: 'ladder',
    title: '축머리! 쫓아가자 (3)',
    emoji: '🏃',
    hint: '⚪백돌이 도망가도 계속 쫓아가!',
    boardSize: 9,
    multiMove: true,
    board: [
      {r:5,c:4,color:W},
      {r:4,c:4,color:B},{r:5,c:3,color:B},
      {r:6,c:5,color:B},
    ],
    correct: [{r:5,c:5}],
    opponentMove: {r:4,c:5,color:W},
    secondCorrect: [{r:4,c:6}],
  },
  // 환격(snapback): 잡히게 두고 다시 잡기
  {
    id: 14,
    type: 'snapback',
    title: '환격! 미끼를 던져! (1)',
    emoji: '🪤',
    hint: '일부러 잡히게 두면 더 많이 잡을 수 있어!',
    boardSize: 9,
    multiMove: true,
    board: [
      // 백돌 3개가 활로 1개 상태, 흑이 미끼를 던져 백이 잡으면 역으로 잡힘
      {r:3,c:3,color:W},{r:3,c:4,color:W},{r:4,c:4,color:W},
      {r:2,c:3,color:B},{r:2,c:4,color:B},{r:3,c:5,color:B},
      {r:4,c:5,color:B},{r:5,c:4,color:B},{r:4,c:3,color:B},
      {r:5,c:3,color:B},
    ],
    // 흑 (3,2)에 두면 → 백 (4,2)로 잡으려 함 → 흑 (3,2)... 
    // 실제: 흑이 (5,5)에 두면? 아니, 단순하게:
    // 흑 (3,2)에 두면 백 전체 활로 0 → 바로 잡힘. 이건 1수.
    // 환격: 흑이 스스로 잡히는 곳에 두고, 상대가 잡으면 더 큰 그룹이 잡힘
    // 재설계: 
    correct: [{r:3,c:2}],
    opponentMove: {r:4,c:2,color:W},
    secondCorrect: [{r:5,c:2}],
  },
  {
    id: 15,
    type: 'snapback',
    title: '환격! 미끼를 던져! (2)',
    emoji: '🪤',
    hint: '한 개를 희생하면 여러 개를 잡을 수 있어!',
    boardSize: 9,
    multiMove: true,
    board: [
      {r:4,c:3,color:W},{r:4,c:4,color:W},{r:3,c:4,color:W},
      {r:3,c:3,color:B},{r:2,c:4,color:B},{r:3,c:5,color:B},
      {r:4,c:5,color:B},{r:5,c:4,color:B},{r:5,c:3,color:B},
    ],
    correct: [{r:4,c:2}],
    opponentMove: {r:5,c:2,color:W},
    secondCorrect: [{r:6,c:2}],
  },
  {
    id: 16,
    type: 'snapback',
    title: '환격! 미끼를 던져! (3)',
    emoji: '🪤',
    hint: '용감하게 들어가! 상대가 잡으면 역전!',
    boardSize: 9,
    multiMove: true,
    board: [
      {r:2,c:5,color:W},{r:2,c:6,color:W},{r:3,c:6,color:W},
      {r:1,c:5,color:B},{r:1,c:6,color:B},{r:2,c:7,color:B},
      {r:3,c:7,color:B},{r:4,c:6,color:B},{r:4,c:5,color:B},
      {r:3,c:5,color:B},
    ],
    correct: [{r:2,c:4}],
    opponentMove: {r:3,c:4,color:W},
    secondCorrect: [{r:4,c:4}],
  },
  // 연결 끊기: 상대 돌 분리
  {
    id: 17,
    type: 'cut',
    title: '연결을 끊어! (1)',
    emoji: '✂️',
    hint: '⚪백돌 사이를 끊어서 약하게 만들어!',
    boardSize: 9,
    multiMove: true,
    board: [
      {r:3,c:3,color:W},{r:3,c:5,color:W},
      {r:3,c:4,color:B},{r:4,c:5,color:B},
      {r:2,c:4,color:B},
    ],
    // 흑 (4,3)에 두면 백 (3,3) 활로 줄임 → 백 (4,4)로 연결 시도 → 흑 (4,4)... 아 그건 이미 차지
    // 단순: 흑 (2,3)에 두면 → 백 (2,5)로 도망 → 흑 (3,6)으로 잡기
    correct: [{r:4,c:3}],
    opponentMove: {r:4,c:4,color:W},
    secondCorrect: [{r:5,c:4}],
  },
  {
    id: 18,
    type: 'cut',
    title: '연결을 끊어! (2)',
    emoji: '✂️',
    hint: '중요한 곳을 끊으면 ⚪백돌이 약해져!',
    boardSize: 9,
    multiMove: true,
    board: [
      {r:4,c:3,color:W},{r:4,c:5,color:W},
      {r:4,c:4,color:B},{r:5,c:5,color:B},
      {r:3,c:4,color:B},
    ],
    correct: [{r:5,c:3}],
    opponentMove: {r:5,c:4,color:W},
    secondCorrect: [{r:6,c:4}],
  },
  // 살리기: 내 돌을 2수로 살리기
  {
    id: 19,
    type: 'save',
    title: '내 돌을 살려! (1)',
    emoji: '💪',
    hint: '⚫흑돌을 연결해서 활로를 만들어!',
    boardSize: 9,
    multiMove: true,
    board: [
      {r:4,c:4,color:B},
      {r:3,c:4,color:W},{r:4,c:3,color:W},{r:5,c:4,color:W},
      {r:4,c:6,color:B},
    ],
    // 흑 (4,5)로 연결 → 백 (3,5)로 압박 → 흑 (3,6)으로 활로 확보
    correct: [{r:4,c:5}],
    opponentMove: {r:3,c:5,color:W},
    secondCorrect: [{r:3,c:6}],
  },
  {
    id: 20,
    type: 'save',
    title: '내 돌을 살려! (2)',
    emoji: '💪',
    hint: '도망가서 활로를 늘려!',
    boardSize: 9,
    multiMove: true,
    board: [
      {r:3,c:3,color:B},
      {r:2,c:3,color:W},{r:3,c:2,color:W},{r:4,c:3,color:W},
      {r:3,c:5,color:B},
    ],
    // 흑 (3,4) 연결 → 백 (2,4) 압박 → 흑 (2,5) 활로 확보
    correct: [{r:3,c:4}],
    opponentMove: {r:2,c:4,color:W},
    secondCorrect: [{r:2,c:5}],
  },
];
